# Generated by Django 3.2.13 on 2022-06-11 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipesite', '0006_alter_recipe_cuisine'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='cuisine',
            field=models.IntegerField(choices=[(0, 'Italian'), (1, 'Indian'), (2, 'Chinese'), (3, 'Thai'), (4, 'American')], default=1),
        ),
    ]
