# Generated by Django 3.2.13 on 2022-06-13 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipesite', '0007_alter_recipe_cuisine'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='cuisine',
            field=models.IntegerField(choices=[(0, 'Italian'), (1, 'Indian'), (2, 'Chinese'), (3, 'Thai'), (4, 'American'), (5, 'Mexican'), (6, 'Middle Eastern'), (7, 'Miscellaneous')], default=1),
        ),
    ]
