# Generated by Django 3.2.13 on 2022-06-15 20:43

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('recipesite', '0009_auto_20220613_0912'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='post',
            new_name='recipe',
        ),
        migrations.AlterField(
            model_name='recipe',
            name='cuisine',
            field=models.IntegerField(choices=[(0, 'Italian'), (1, 'Indian'), (2, 'Chinese'), (3, 'Thai'), (4, 'American'), (5, 'Mexican'), (6, 'Middle Eastern'), (7, 'Miscellaneous')], default=0),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='ingredients',
            field=tinymce.models.HTMLField(),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='method',
            field=tinymce.models.HTMLField(null=True),
        ),
    ]
